api_keys:
  polygon: "70D7rupiLla29W4BPvlIr9UGp25_XnuQ"
  tipranks: ""
  smtp:
  host: smtp.gmail.com
  port: 587
  email: your_email@gmail.com
  password: your_app_password
  to: notify_user@example.com
